@echo off
echo Starting 3D Prototype...
echo Starting Backend Server on port 5000...
start "Backend Server" cmd /k "cd server && npm start"
echo Starting Frontend Client on port 3000...
start "Frontend Client" cmd /k "cd client && npm start"
echo Done! Both servers are starting up.
